### ISSUE TITLE
Problem booting from EMMC image

### ISSUE THREAD

**Issue by coldBug** [mammo0/openwrt-bpi-r2#3]
Hi mammo0,
thanks a lot for your BPI-R2 images. They help a lot :)

Booting your SD image works great out of the box. I then followed your README to boot from EMMC and have successfully written both images to it.

`mmcblk0      179:0    0  7.3G  0 disk`
`├─mmcblk0p1  179:1    0  9.6M  0 part`
`└─mmcblk0p2  179:2    0 47.7M  0 part`
`mmcblk0boot0 179:8    0    4M  1 disk`

Then I tried booting from EMMC but it failed. Using a UART connection I got the following error message:

`bootargs=earlyprintk console=ttyS0,115200 console=tty1 fbcon=map:0 root=/dev/mmcblk0p2` `rootfstype=ext4 roo7`
`Wrong Image Format for bootm command`
`ERROR: can't get kernel image!`

Any ideas? The EMMC flash is correctly addressed as 'mmcblk0' in UBOOT.
Thanks a lot!
cold

**Comment by mammo0** [comment]
Hello @coldBug,

first thanks for your feedback.

To your problem: I'm sorry but I can't reproduce that behaviour. Just now I flashed the latest EMMC image (incl. the boot image) that I've downloaded from the release page to the MMC of my R2. I followed the two steps of the README.
But the boot process afterwards does not show any errors on UART and it boots successfully and I can login via SSH/UART.

So, are you using the precompiled images from the repo, or did you built the images yourself?

**Comment by coldBug** [comment]
Thanks for your fast reply!
I used your precompiled images and followed the README.

1. Downloaded all 3 images
2. Installed SD image with dd `dd if=BPI-R2_SD.img of=/dev/sda`
3. Booted SD image
4. Copied both EMMC images with SCP to /tmp
5. Then I check that the EMMC is mapped as 'mmcblk0' → was true
6. Installed with `dd if=BPI-R2_EMMC.img of=/dev/mmcblk0`, `echo 0 > /sys/block/mmcblk0boot0/force_ro` and `dd if=BPI-R2_EMMC_boot0.img of=/dev/mmcblk0boot0`
7. Images were successfully transfered...

Do I have to flash something to the EMMC before using your images? Is there something to change in UBOOT I missed? Any UBOOT commands I could run to give you some insights?

Maybe there is something left on the EMMC flash? I'm going to try to overwrite the boot partition with zeros first...

**Comment by mammo0** [comment]
Strange... Did you select "Boot from eMMC." in the U-Boot menu? Or did you use the default bootmenu entry?

Because if I select "Boot from SD." and no SD-card is present, then I get a similar error message.

So maybe an U-Boot variable has a wrong value. Can you please go to the U-Boot console (select it from the bootmenu) and paste the output of `printenv` here? Please do it after a fresh restart.

Mine is:

```
askdtb=askenv dtbinput "enter dtb-name:";
askkernel=askenv kernelinput "enter uImage-name:";
boot0=run lskernel;run askkernel;if printenv kernelinput ;then setenv kernel ${kernelinput};run lsdtb;run askdtb;if printenv dtbinput ;then setenv fdt ${dtbinput};fi; run newboot2; fi;
boot1=run newboot;
bootall=if printenv fdt; then run loadfdt; if printenv dtolist;then run loaddtolist;fi; bootm ${loadaddr} - ${dtaddr} ;else bootm; fi
bootargs=console=ttyS0,115200 root=/dev/mmcblk1p2 rw rootwait ip=dhcp
bootcmd=setenv bootdelay 3; run reloadmenu;
bootdelay=0
bootdev=eMMC
bootedfrom=eMMC
bootenv=uEnv.txt
bootfile=uImage
bootmenu_0=1. Enter kernel-name to boot from SD/EMMC.=run boot0
bootmenu_1=2. Boot kernel from TFTP.=run bootnet
bootmenu_2=3. Boot from SD/EMMC.=run boot1
bootmenu_3=4. Boot from eMMC.=run useemmc; run boot1
bootmenu_4=5. Boot from SD.=run usesd; run boot1
bootmenu_default=2
bootnet=run lstftp;run askkernel;if printenv kernelinput ;then setenv bootfile "${kernelinput}"; fi;printenv; setenv bootargs ${netbootargs};tftp ${loadaddr} ${bootfile};bootm
bootopts=vmalloc=496M debug=7 initcall_debug=0
buildargs=setenv bootargs "${console} root=${root} ${bootopts} ${graphic}"
checkbootedfrom=if itest.l *81dffff0 == 434d4d65 ; then setenv bootedfrom eMMC; else setenv bootedfrom SD; fi;
checkenv=test -e ${device} ${partition} ${bootenv}
checkmmc=fatinfo ${device} 0:1
checkroot=fatinfo ${device} ${partition}
checksd=fatinfo ${device} 1:1
console=earlyprintk console=ttyS0,115200 console=tty1 fbcon=map:0
detectroot=run useemmc; run checkbootedfrom; if test "${bootedfrom}" == "SD"; then run usesd; fi; run validateroot;
device=mmc
dtaddr=0x83f00000
fdt_high=0xffffffff
fdtcontroladdr=ffb94000
fileaddr=83000000
filesize=11e2
graphic=video=1920x1080 drm.debug=0x7
importenv=env import -t ${scriptaddr} ${filesize}
ipaddr=192.168.0.11
kernel=uImage
loadaddr=0x80200000
loadbootenv=if fatload ${device} ${partition} ${scriptaddr} ${bootenv};then run importenv;else echo "fatload (${bootenv}) failed";fi
loaddto=echo "loaddto:${dto}";fdt addr ${dtaddr};fdt resize 8192; setexpr fdtovaddr ${dtaddr} + F000;fatload ${device} ${partition} ${fdtovaddr} dtb/${dto} && fdt apply ${fdtovaddr}
loaddtolist=for dto in ${dtolist} ; do run loaddto ; done
loadfdt=fatload ${device} ${partition} ${dtaddr} dtb/${fdt}
loadkernel=echo "loading kernel ${kernel}...";fatload ${device} ${partition} ${loadaddr} ${kernel}
lsdtb=ls ${device} ${partition} dtb
lskernel=ls ${device} ${partition};
lstftp=tftp ${loadaddr} ${serverip}:files.lst;setexpr listend ${loadaddr} + ${filesize};mw.b ${listend} 00 2;strings ${loadaddr};
netbootargs=console=ttyS0,115200 root=/dev/mmcblk1p2 rw rootwait
netmask=255.255.255.0
newboot=run prepsetroot; run setroot;run buildargs;printenv bootargs;fatload ${device} ${partition} ${loadaddr} ${kernel}; bootm
newboot2=run prepsetroot; run setroot;run buildargs; printenv bootargs; run loadkernel; run bootall;
partition=0:1
prepsetroot=setenv setroot setenv root ${roottmpl}
reloadenv=run detectroot; if run validroot; then if run checkenv; then run loadbootenv; run detectroot; else echo uEnv.txt file not found on ${bootdev}; fi; fi;
reloadmenu=run reloadenv; run reportboot; if run validroot; then if run checkenv; then run loadbootenv; else echo uEnv.txt file not found on ${bootdev}; fi; bootmenu; fi;
reportboot=run reportbootedfrom reportvalidroot reportrootswapwarn reportbootdev
reportbootdev=echo "Booting from ${bootdev}."
reportbootedfrom=echo "Preloader/U-Boot loaded from ${bootedfrom}."; run validroot || echo "Both SD and eMMC pt#1 are not FAT, falling back to U-Boot shell."
reportrootswapwarn=if test "${bootedfrom}" != "${bootdev}" ; then echo "Warning: Partition 1 on ${bootedfrom} is not FAT, failing back to ${bootdev}"; fi; true;
reportvalidroot=run validroot || echo "Both SD and eMMC pt#1 are not FAT, falling back to U-Boot shell."
resetenv=env default -a;printenv;
rootdev=/dev/mmcblk0p2
roottmpl=${rootdev} rootfstype=ext4 rootwait
scriptaddr=0x83000000
serverip=192.168.0.10
swaproot=run usesd
useemmc=setenv partition 0:1; setenv rootdev /dev/mmcblk0p2; setenv bootdev eMMC; setenv swaproot 'run usesd';
usesd=setenv partition 1:1; setenv rootdev /dev/mmcblk1p2; setenv bootdev SD; setenv swaproot 'run useemmc';
validateroot=setenv validroot false; run checkroot || run swaproot; run checkroot && setenv validroot true || run swaproot;
validroot=true
```

**Comment by coldBug** [comment]
Sure thing, I tried both - using SD/EMMC is only booting SD and boot EMMC did not work, here is the env:

```askdtb=askenv dtbinput "enter dtb-name:";
askkernel=askenv kernelinput "enter uImage-name:";
boot0=run lskernel;run askkernel;if printenv kernelinput ;then setenv kernel ${kernelinput};run lsdtb;run askdtb;if printenv dtbinput ;then setenv fdt ${dtbinput};fi; run newboot2; fi;
boot1=run newboot;
bootall=if printenv fdt; then run loadfdt; if printenv dtolist;then run loaddtolist;fi; bootm ${loadaddr} - ${dtaddr} ;else bootm; fi
bootargs=console=ttyS0,115200 root=/dev/mmcblk1p2 rw rootwait ip=dhcp
bootcmd=setenv bootdelay 3; run reloadmenu;
bootdelay=0
bootdev=SD
bootedfrom=SD
bootenv=uEnv.txt
bootfile=uImage
bootmenu_0=1. Enter kernel-name to boot from SD/EMMC.=run boot0
bootmenu_1=2. Boot kernel from TFTP.=run bootnet
bootmenu_2=3. Boot from SD/EMMC.=run boot1
bootmenu_3=4. Boot from eMMC.=run useemmc; run boot1
bootmenu_4=5. Boot from SD.=run usesd; run boot1
bootmenu_default=2
bootnet=run lstftp;run askkernel;if printenv kernelinput ;then setenv bootfile "${kernelinput}"; fi;printenv; setenv bootargs ${netbootargs};tftp ${loadaddr} ${bootfile};bootm
bootopts=vmalloc=496M debug=7 initcall_debug=0
buildargs=setenv bootargs "${console} root=${root} ${bootopts} ${graphic}"
checkbootedfrom=if itest.l *81dffff0 == 434d4d65 ; then setenv bootedfrom eMMC; else setenv bootedfrom SD; fi;
checkenv=test -e ${device} ${partition} ${bootenv}
checkmmc=fatinfo ${device} 0:1
checkroot=fatinfo ${device} ${partition}
checksd=fatinfo ${device} 1:1
console=earlyprintk console=ttyS0,115200 console=tty1 fbcon=map:0
detectroot=run useemmc; run checkbootedfrom; if test "${bootedfrom}" == "SD"; then run usesd; fi; run validateroot;
device=mmc
dtaddr=0x83f00000
fdt_high=0xffffffff
fdtcontroladdr=ffb94000
fileaddr=83000000
filesize=11e2
graphic=video=1920x1080 drm.debug=0x7
importenv=env import -t ${scriptaddr} ${filesize}
ipaddr=192.168.0.11
kernel=uImage
loadaddr=0x80200000
loadbootenv=if fatload ${device} ${partition} ${scriptaddr} ${bootenv};then run importenv;else echo "fatload (${bootenv}) failed";fi
loaddto=echo "loaddto:${dto}";fdt addr ${dtaddr};fdt resize 8192; setexpr fdtovaddr ${dtaddr} + F000;fatload ${device} ${partition} ${fdtovaddr} dtb/${dto} && fdt apply ${fdtovaddr}
loaddtolist=for dto in ${dtolist} ; do run loaddto ; done
loadfdt=fatload ${device} ${partition} ${dtaddr} dtb/${fdt}
loadkernel=echo "loading kernel ${kernel}...";fatload ${device} ${partition} ${loadaddr} ${kernel}
lsdtb=ls ${device} ${partition} dtb
lskernel=ls ${device} ${partition};
lstftp=tftp ${loadaddr} ${serverip}:files.lst;setexpr listend ${loadaddr} + ${filesize};mw.b ${listend} 00 2;strings ${loadaddr};
netbootargs=console=ttyS0,115200 root=/dev/mmcblk1p2 rw rootwait
netmask=255.255.255.0
newboot=run prepsetroot; run setroot;run buildargs;printenv bootargs;fatload ${device} ${partition} ${loadaddr} ${kernel}; bootm
newboot2=run prepsetroot; run setroot;run buildargs; printenv bootargs; run loadkernel; run bootall;
partition=1:1
prepsetroot=setenv setroot setenv root ${roottmpl}
reloadenv=run detectroot; if run validroot; then if run checkenv; then run loadbootenv; run detectroot; else echo uEnv.txt file not found on ${bootdev}; fi; fi;
reloadmenu=run reloadenv; run reportboot; if run validroot; then if run checkenv; then run loadbootenv; else echo uEnv.txt file not found on ${bootdev}; fi; bootmenu; fi;
reportboot=run reportbootedfrom reportvalidroot reportrootswapwarn reportbootdev
reportbootdev=echo "Booting from ${bootdev}."
reportbootedfrom=echo "Preloader/U-Boot loaded from ${bootedfrom}."; run validroot || echo "Both SD and eMMC pt#1 are not FAT, falling back to U-Boot shell."
reportrootswapwarn=if test "${bootedfrom}" != "${bootdev}" ; then echo "Warning: Partition 1 on ${bootedfrom} is not FAT, failing back to ${bootdev}"; fi; true;
reportvalidroot=run validroot || echo "Both SD and eMMC pt#1 are not FAT, falling back to U-Boot shell."
resetenv=env default -a;printenv;
rootdev=/dev/mmcblk1p2
roottmpl=${rootdev} rootfstype=ext4 rootwait
scriptaddr=0x83000000
serverip=192.168.0.10
swaproot=run useemmc
useemmc=setenv partition 0:1; setenv rootdev /dev/mmcblk0p2; setenv bootdev eMMC; setenv swaproot 'run usesd';
usesd=setenv partition 1:1; setenv rootdev /dev/mmcblk1p2; setenv bootdev SD; setenv swaproot 'run useemmc';
validateroot=setenv validroot false; run checkroot || run swaproot; run checkroot && setenv validroot true || run swaproot;
validroot=true

Environment size: 4409/8188 bytes

**Comment by mammo0** [comment]
Thank you.

I compared both. The only difference is the current `bootdev` variable (and corresponding ones) pointing to the SD card in your environment. But this is normal if you the SD card was inserted during boot. Because U-Boot is configured to boot first the SD card and then falls back to eMMC.

May you try to boot without the SD card inserted? But normally it should also boot with it...

**Comment by coldBug** [comment]
Seems like I can't! When trying to boot without SD card nothing happens... I don't get any output from UART debugging.

**Comment by mammo0** [comment]
I can reproduce this behaviour, if I clear the `mmcblk0boot0` partition. Then no booting is possible.

So are you sure that there is any data on that partition?

**Comment by coldBug** [comment]
```
dd if=/dev/zero of=/dev/mmcblk0boot0
dd: writing '/dev/mmcblk0boot0': No space left on device
8193+0 records in
8192+0 records out

dd if=BPI-R2_EMMC_boot0.img of=/dev/mmcblk0boot0
183+1 records in
183+1 records out

Booting from EMMC:
bootargs=earlyprintk console=ttyS0,115200 console=tty1 fbcon=map:0 root=/dev/mmcblk0p2 rootfstype=ex7
Wrong Image Format for bootm command
ERROR: can't get kernel image!

Booting without SD:
nothing happens, so it can't find the bootloader...

**Comment by mammo0** [comment]
Ok thanks for retrying.

Meanwhile I found something: https://fw-web.de/dokuwiki/doku.php?id=en/bpi-r2/uboot

What is the output of `mmc partconf 0` on the u-boot console on your R2?
The `0` should be the number of the eMMC device. You get the correct number from `mmc list` command.


The output should be:

```
EXT_CSD[179], PARTITION_CONFIG:
BOOT_ACK: 0x1
BOOT_PARTITION_ENABLE: 0x1
PARTITION_ACCESS: 0x0
```

If your output is different please try this command: `mmc partconf 0 1 1 0`
The first `0` should be the number of the eMMC device like above.

And then try a reboot from eMMC.

**Comment by coldBug** [comment]
Sure! Thanks for helping out! Well there is definitive something broken, I don't get any output at all and reboot gives the same error as before:
```
BPI-R2> mmc list
mmc@11230000: 0
mmc@11240000: 1 (SD)
BPI-R2> mmc partconf 0
BPI-R2> mmc partconf 0 1 1 0
BPI-R2> mmc partconf 0      
BPI-R2>

**Comment by mammo0** [comment]
Yeah, you're right there should be at least some output...

Also I got more output from `mmc list` command:

```
mmc@11230000: 0 (eMMC)
mmc@11240000: 1 (SD)
```

Maybe `mmc rescan` helps?

**Comment by coldBug** [comment]
Nothing happens, that doesn't make sense at all:
```
BPI-R2> mmc list
mmc@11230000: 0
mmc@11240000: 1 (SD)
BPI-R2> mmc rescan
BPI-R2> mmc list
mmc@11230000: 0
mmc@11240000: 1 (SD)
```

I can switch to dev 1 but when I try to switch back nothing happens:
```
BPI-R2> mmc part
BPI-R2> mmc dev 1
switch to partitions #0, OK
mmc1 is current device
BPI-R2> mmc part

Partition Map for MMC device 1  --   Partition Type: DOS

Part    Start Sector    Num Sectors     UUID            Type
  1     9766            19532           f04864d5-01     0b
  2     29298           15402382        f04864d5-02     83
BPI-R2> mmc list
mmc@11230000: 0
mmc@11240000: 1 (SD)
BPI-R2> mmc dev 0
BPI-R2> mmc part

```
Maybe writing to EMMC from SD card doesn't work? You wrote to it using your EMMC system, right? Seems to me like mmc dev 0 is empty?

**Comment by mammo0** [comment]
Ok, seems U-Boot doesn't detect your eMMC device right.
Unfortunately I do not have any deep knowledge about U-Boot to debug this...

> Maybe writing to EMMC from SD card doesn't work? You wrote to it using your EMMC system, right? Seems to me like mmc dev 0 is empty?

I've written the images to eMMC when the R2 was booted from SD card like I have described it in the README.

**Comment by mammo0** [comment]
Maybe a newer U-Boot version helps. I'm using the `2019-01-bpi-r2` branch of https://github.com/frank-w/u-boot. Meanwhile he released newer versions of U-Boot for the R2. There are also precompiled images in his repository.

If you want to compile a newer version, change the `UBOOT_VER` variable in the .env file to the desired branch name from the u-boot repo. Then run `1_build_uboot.sh`.

You can move the compiled image to the artifacts directory of my repository and rename it to `u-boot.bin`. Then you can build the eMMC image with the `3_build_images.sh` script. But first you must build OpenWRT.

**Comment by coldBug** [comment]
Thanks a lot for your help! I will give it a try and post feedback later :)

**Comment by mammo0** [comment]
Please checkout the following eMMC images: [uboot-2020-10-bpi.zip](https://github.com/mammo0/openwrt-bpi-r2/files/5972146/uboot-2020-10-bpi.zip)

I used the current default branch `2020-10-bpi` of the u-boot repo. This one does also boot fine for me.

**Comment by coldBug** [comment]
Thanks for sharing your build - I was done as well building it with the 2020-10-bpi branch and OpenWrt 19.07.5.

Sadly I still get the same errors - with your as well as with my build. :(

**Comment by mammo0** [comment]
Ok, sorry that I couldn't help you, but that was my last idea...
I think, it has something to do with U-Boot that is not detecting your eMMC device probably. But since I can't reproduce that behaviour, I've got no clue where the problem is.

Maybe you can contact @frank-w if he has an idea.

If you find a solution to your problem, please share it here.

**Comment by frank-w** [comment]
Have not read the full thread,but have you checked partition-config?

Afair you need to change to emmc first...my uboot selects sdcard if it was booted from it

mmc dev 0
mmc partconf 0 1 1 0

**Comment by coldBug** [comment]
@frank-w thanks a lot for helping! The Problem is, that `mmc dev 0` doesn't seem to work and nothing is printed on the cmd. When I run `mmc dev 1` I get some feedback:
```                                                                                   
switch to partitions #0, OK                                                                          
mmc1 is current device
```
When running both your commands, I get not return values at all:
```
BPI-R2> mmc dev 0                                                                                    
BPI-R2> mmc partconf 0 1 1 0                                                                         
BPI-R2> 
```
When using `mmc list`:
```
mmc@11230000: 0                                                                                      
mmc@11240000: 1 (SD) 
```
The first response is missing the (eMMC) part. Any ideas? I have tried your uboot kernel `2020-10-bpi` and `2019-01-bpi-r2`.

**Comment by coldBug** [comment]
@mammo0  @frank-w I've built the OpenWRT dev branch with kernel 5.4 - turns out the bootloader delivered with it works on my device! The bootloader now detected the eMMC memory, and I was able to copy and boot from eMMC.

**Comment by frank-w** [comment]
i don't think it is a kernel-problem which is loaded after uboot, but i guess something else has changed...maybe the preloader...afair there was a change in 2019-10, which fixes problems with bigger uboot-binaries...i see only BPI-R2_EMMC_boot0.img in your log

maybe you can byte-comapre with this one:
BPI-R2-EMMC-boot0-DDR1600-20191024-0k.img.gz 
on
https://github.com/BPI-SINOVOIP/BPI-files/tree/master/SD/100MB

also there was a problem in openwrt creating the HEAD-data (HEAD0/HEAD1) because of script running with /bin/sh instead of bash (need to support echo -e for escape-sequences)...but in this case you cannot boot to uboot...

but good to know it works now :)

**Comment by coldBug** [comment]
@frank-w I was able to boot the eMMC image from this repository by first flashing the OpenWrt master branch image I built onto it and then using `dd` to overwrite the data partition with the `BPI-R2_EMMC.img` provided here.

I did not reflash the preloader image `BPI-R2_EMMC_boot0.img` - so I guess there was the problem. This repository uses the `BPI-R2-EMMC-boot0-DDR1600-20191024-0k.img.gz` image you just linked, so this is very strange...

**Comment by mammo0** [comment]
So, does it work now for you?

I'm sorry, but I don't understand what images you have flashed.

**Comment by coldBug** [comment]
@mammo0 I now have your image installed but used the preloader from my self compiled OpenWrt dev release with 5.4 kernel. Meaning I didn't flash your 'BPI-R2_EMMC_boot0.img' image. The problem seemed to be with the preloader or something else related with flashing it. Meaning the problem is not with your images, so I'm closing the issue now!

**Comment by mammo0** [comment]
Thanks for clarification.

But indeed very strange that the `PI-R2_EMMC_boot0.img` did not work.
